package generator

import (
	"fmt"
	"go/ast"
	"go/token"
	"strings"

	"github.com/mateothegreat/go-config/scanner"
)

// ASTCodeGenerator generates validation code using AST manipulation
// This replaces the template-based approach for better performance and type safety
type ASTCodeGenerator struct {
	config     GeneratorConfig
	fset       *token.FileSet
	imports    map[string]string   // alias -> import path
	validators map[string]ast.Expr // cache of validator expressions
	registry   *ValidatorRegistry
}

// NewASTCodeGenerator creates a new AST-based code generator
func NewASTCodeGenerator(config GeneratorConfig) *ASTCodeGenerator {
	return &ASTCodeGenerator{
		config:     config,
		fset:       token.NewFileSet(),
		imports:    make(map[string]string),
		validators: make(map[string]ast.Expr),
		registry:   NewValidatorRegistry(),
	}
}

// GenerateFile generates a complete validation file using AST
func (g *ASTCodeGenerator) GenerateFile(structs []scanner.StructInfo, packageName string) (string, error) {
	// Build the file content manually with proper formatting
	var buf strings.Builder

	// Write header comments
	buf.WriteString("// Code generated by go-config. DO NOT EDIT.\n")
	buf.WriteString("// This file contains zero-reflection validation methods.\n\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", packageName))

	// Setup imports
	g.setupImports(structs)

	// Write imports
	buf.WriteString("import (\n")
	// Add standard library imports needed for validation
	buf.WriteString("\t\"fmt\"\n")
	buf.WriteString("\t\"regexp\"\n")
	buf.WriteString("\t\"net\"\n")
	buf.WriteString("\t\"net/url\"\n")
	buf.WriteString("\n")
	for alias, path := range g.imports {
		if alias != "" && alias != path[strings.LastIndex(path, "/")+1:] {
			buf.WriteString(fmt.Sprintf("\t%s \"%s\"\n", alias, path))
		} else {
			buf.WriteString(fmt.Sprintf("\t\"%s\"\n", path))
		}
	}
	buf.WriteString(")\n\n")

	// Add validation helper functions and patterns
	buf.WriteString("// Validation patterns\n")
	buf.WriteString("var (\n")
	buf.WriteString("\temailRegex = regexp.MustCompile(`^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$`)\n")
	buf.WriteString("\turlRegex = regexp.MustCompile(`^[a-zA-Z][a-zA-Z0-9+.-]*://[^\\s]*$`)\n")
	buf.WriteString("\talphaRegex = regexp.MustCompile(`^[a-zA-Z]+$`)\n")
	buf.WriteString("\talphaNumRegex = regexp.MustCompile(`^[a-zA-Z0-9]+$`)\n")
	buf.WriteString("\tnumericRegex = regexp.MustCompile(`^[0-9]+$`)\n")
	buf.WriteString("\tuuidRegex = regexp.MustCompile(`^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`)\n")
	buf.WriteString("\tbase64Regex = regexp.MustCompile(`^[A-Za-z0-9+/]*={0,2}$`)\n")
	buf.WriteString(")\n\n")

	// Add helper functions
	buf.WriteString("// Helper validation functions\n")
	buf.WriteString("func isValidEmail(email string) bool {\n")
	buf.WriteString("\treturn emailRegex.MatchString(email)\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func isValidURL(u string) bool {\n")
	buf.WriteString("\t_, err := url.Parse(u)\n")
	buf.WriteString("\treturn err == nil && urlRegex.MatchString(u)\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func isValidAlpha(s string) bool {\n")
	buf.WriteString("\treturn alphaRegex.MatchString(s)\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func isValidAlphanum(s string) bool {\n")
	buf.WriteString("\treturn alphaNumRegex.MatchString(s)\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func isValidNumeric(s string) bool {\n")
	buf.WriteString("\treturn numericRegex.MatchString(s)\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func isValidBase64(s string) bool {\n")
	buf.WriteString("\treturn base64Regex.MatchString(s) && len(s)%4 == 0\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func isValidHostname(s string) bool {\n")
	buf.WriteString("\t// Simple hostname validation\n")
	buf.WriteString("\thostnameRegex := regexp.MustCompile(`^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$`)\n")
	buf.WriteString("\treturn hostnameRegex.MatchString(s)\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func isValidCidr(s string) bool {\n")
	buf.WriteString("\t_, _, err := net.ParseCIDR(s)\n")
	buf.WriteString("\treturn err == nil\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func isValidIP(s string) bool {\n")
	buf.WriteString("\treturn net.ParseIP(s) != nil\n")
	buf.WriteString("}\n\n")

	// Generate init function
	buf.WriteString("// init registers generated validators with the go-validation registry\n")
	buf.WriteString("func init() {\n")
	for _, structInfo := range structs {
		buf.WriteString(fmt.Sprintf("\tvalidation.RegisterValidation(\"%s\", Validate%s)\n",
			strings.ToLower(structInfo.Name), structInfo.Name))
	}
	buf.WriteString("}\n\n")

	// Generate validation methods for each struct
	for _, structInfo := range structs {
		// Generate the Validate() method
		buf.WriteString(fmt.Sprintf("// Validate validates the %s struct using zero-reflection validation\n", structInfo.Name))
		buf.WriteString(fmt.Sprintf("func (s *%s) Validate() error {\n", structInfo.Name))
		buf.WriteString("\tvar errs *errors.FluentError = errors.NewError()\n")

		// Generate validation for each field
		for _, field := range structInfo.Fields {
			if len(field.ValidateRules) == 0 {
				continue
			}

			buf.WriteString(fmt.Sprintf("\n\t// Validate %s\n", field.Name))
			for rule, value := range field.ValidateRules {
				validationCode := g.generateValidationCode(field, rule, value)
				if validationCode != "" {
					buf.WriteString(validationCode)
				}
			}
		}

		buf.WriteString("\n\tif errs.HasErrors() {\n")
		buf.WriteString("\t\treturn errs\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\treturn nil\n")
		buf.WriteString("}\n\n")

		// Generate the standalone validator function
		buf.WriteString(fmt.Sprintf("// Validate%s validates %s instances for use with go-validation registry\n",
			structInfo.Name, structInfo.Name))
		buf.WriteString(fmt.Sprintf("func Validate%s(fl validation.FieldLevel) bool {\n", structInfo.Name))
		buf.WriteString("\t// This is a placeholder - actual implementation would use fl\n")
		buf.WriteString("\treturn true\n")
		buf.WriteString("}\n\n")
	}

	return buf.String(), nil
}

// generateValidationCode generates the validation code for a specific field and rule
func (g *ASTCodeGenerator) generateValidationCode(field scanner.FieldInfo, rule, value string) string {
	var code strings.Builder

	// Get validator info
	info, exists := g.registry.validators[rule]

	switch rule {
	case "required":
		switch field.Type {
		case "string":
			code.WriteString(fmt.Sprintf("\tif s.%s == \"\" {\n", field.Name))
			code.WriteString(fmt.Sprintf("\t\terrs.Field(\"%s\").Required()\n", field.Name))
			code.WriteString("\t}\n")
		case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64":
			code.WriteString(fmt.Sprintf("\tif s.%s == 0 {\n", field.Name))
			code.WriteString(fmt.Sprintf("\t\terrs.Field(\"%s\").Required()\n", field.Name))
			code.WriteString("\t}\n")
		case "float32", "float64":
			code.WriteString(fmt.Sprintf("\tif s.%s == 0.0 {\n", field.Name))
			code.WriteString(fmt.Sprintf("\t\terrs.Field(\"%s\").Required()\n", field.Name))
			code.WriteString("\t}\n")
		case "bool":
			code.WriteString(fmt.Sprintf("\tif !s.%s {\n", field.Name))
			code.WriteString(fmt.Sprintf("\t\terrs.Field(\"%s\").Required()\n", field.Name))
			code.WriteString("\t}\n")
		default:
			// For structs and other complex types, just add a comment
			if strings.HasPrefix(field.Type, "[]") {
				code.WriteString(fmt.Sprintf("\tif len(s.%s) == 0 {\n", field.Name))
				code.WriteString(fmt.Sprintf("\t\terrs.Field(\"%s\").Required()\n", field.Name))
				code.WriteString("\t}\n")
			} else if !strings.Contains(field.Type, "*") {
				// Non-pointer struct types can't be nil, so skip
				code.WriteString(fmt.Sprintf("\t// Struct field %s is always initialized\n", field.Name))
			} else {
				code.WriteString(fmt.Sprintf("\tif s.%s == nil {\n", field.Name))
				code.WriteString(fmt.Sprintf("\t\terrs.Field(\"%s\").Required()\n", field.Name))
				code.WriteString("\t}\n")
			}
		}

	case "email":
		// For slice types, validate each element
		if strings.HasPrefix(field.Type, "[]") {
			code.WriteString(fmt.Sprintf("\tfor i, item := range s.%s {\n", field.Name))
			code.WriteString(fmt.Sprintf("\t\tif !isValidEmail(item) {\n"))
			code.WriteString(fmt.Sprintf("\t\t\terrs.Field(fmt.Sprintf(\"%s[%%d]\", i)).Email()\n", field.Name))
			code.WriteString("\t\t}\n")
			code.WriteString("\t}\n")
		} else {
			code.WriteString(fmt.Sprintf("\tif !isValidEmail(s.%s) {\n", field.Name))
			code.WriteString(fmt.Sprintf("\t\terrs.Field(\"%s\").Email()\n", field.Name))
			code.WriteString("\t}\n")
		}

	case "url":
		code.WriteString(fmt.Sprintf("\tif !isValidURL(s.%s) {\n", field.Name))
		code.WriteString(fmt.Sprintf("\t\terrs.Field(\"%s\").URL()\n", field.Name))
		code.WriteString("\t}\n")

	case "max":
		code.WriteString(fmt.Sprintf("\tif s.%s > %s {\n", field.Name, value))
		code.WriteString(fmt.Sprintf("\t\terrs.Field(\"%s\").Max(%s)\n", field.Name, value))
		code.WriteString("\t}\n")

	case "minlen":
		code.WriteString(fmt.Sprintf("\tif len(s.%s) < %s {\n", field.Name, value))
		code.WriteString(fmt.Sprintf("\t\terrs.Field(\"%s\").MinLength(%s)\n", field.Name, value))
		code.WriteString("\t}\n")

	case "maxlen":
		code.WriteString(fmt.Sprintf("\tif len(s.%s) > %s {\n", field.Name, value))
		code.WriteString(fmt.Sprintf("\t\terrs.Field(\"%s\").MaxLength(%s)\n", field.Name, value))
		code.WriteString("\t}\n")

	case "len":
		code.WriteString(fmt.Sprintf("\tif len(s.%s) != %s {\n", field.Name, value))
		code.WriteString(fmt.Sprintf("\t\terrs.Field(\"%s\").Custom(\"must be exactly %s characters\", \"len\")\n", field.Name, value))
		code.WriteString("\t}\n")

	case "oneof":
		// Parse options
		options := strings.Split(value, " ")
		var conditions []string
		var quotedOptions []string
		for _, opt := range options {
			conditions = append(conditions, fmt.Sprintf("s.%s != \"%s\"", field.Name, opt))
			quotedOptions = append(quotedOptions, fmt.Sprintf("\"%s\"", opt))
		}
		code.WriteString(fmt.Sprintf("\tif %s {\n", strings.Join(conditions, " && ")))
		code.WriteString(fmt.Sprintf("\t\terrs.Field(\"%s\").OneOf(%s)\n", field.Name, strings.Join(quotedOptions, ", ")))
		code.WriteString("\t}\n")

	case "dive":
		// Handle slice validation - this should be combined with other rules
		code.WriteString(fmt.Sprintf("\t// Dive validation for %s would validate each element\n", field.Name))

	case "min":
		// Handle min for slices differently
		if strings.HasPrefix(field.Type, "[]") {
			code.WriteString(fmt.Sprintf("\tif len(s.%s) < %s {\n", field.Name, value))
			code.WriteString(fmt.Sprintf("\t\terrs.Field(\"%s\").Custom(\"must have at least %s items\", \"min\")\n", field.Name, value))
			code.WriteString("\t}\n")
		} else {
			code.WriteString(fmt.Sprintf("\tif s.%s < %s {\n", field.Name, value))
			code.WriteString(fmt.Sprintf("\t\terrs.Field(\"%s\").Min(%s)\n", field.Name, value))
			code.WriteString("\t}\n")
		}
		return code.String() // Early return to avoid duplicate case

	case "alpha", "alphanum", "numeric", "base64", "uuid", "ipv4", "ipv6", "ip", "cidr", "hostname", "mac":
		// These would need helper functions or regex patterns
		if exists && !info.RequiresArgs {
			funcName := fmt.Sprintf("isValid%s", strings.Title(rule))
			// Special case for "ip" to maintain uppercase
			if rule == "ip" {
				funcName = "isValidIP"
			}
			// For slice types, validate each element
			if strings.HasPrefix(field.Type, "[]") {
				code.WriteString(fmt.Sprintf("\tfor i, item := range s.%s {\n", field.Name))
				code.WriteString(fmt.Sprintf("\t\tif !%s(item) {\n", funcName))
				code.WriteString(fmt.Sprintf("\t\t\terrs.Field(fmt.Sprintf(\"%s[%%d]\", i)).Format(\"must be a valid %s\")\n", field.Name, rule))
				code.WriteString("\t\t}\n")
				code.WriteString("\t}\n")
			} else {
				code.WriteString(fmt.Sprintf("\tif !%s(s.%s) {\n", funcName, field.Name))
				code.WriteString(fmt.Sprintf("\t\terrs.Field(\"%s\").Format(\"must be a valid %s\")\n", field.Name, rule))
				code.WriteString("\t}\n")
			}
		} else {
			code.WriteString(fmt.Sprintf("\t// TODO: implement %s validation\n", rule))
		}

	default:
		// Handle complex validators like "ip|hostname"
		if strings.Contains(rule, "|") {
			parts := strings.Split(rule, "|")
			var conditions []string
			for _, part := range parts {
				funcName := fmt.Sprintf("isValid%s", strings.Title(part))
				// Special case for "ip" to maintain uppercase
				if part == "ip" {
					funcName = "isValidIP"
				}
				conditions = append(conditions, fmt.Sprintf("%s(s.%s)", funcName, field.Name))
			}
			code.WriteString(fmt.Sprintf("\tif !(%s) {\n", strings.Join(conditions, " || ")))
			code.WriteString(fmt.Sprintf("\t\terrs.Field(\"%s\").Format(\"must be a valid %s\")\n", field.Name, rule))
			code.WriteString("\t}\n")
		} else {
			// For unknown validators, add a TODO comment
			code.WriteString(fmt.Sprintf("\t// TODO: implement %s validation\n", rule))
		}
	}

	return code.String()
}

// setupImports configures the required imports
func (g *ASTCodeGenerator) setupImports(structs []scanner.StructInfo) {
	// Always include validation package for registration
	g.imports["validation"] = "github.com/mateothegreat/go-validation"

	// Always include errors package for error handling
	g.imports["errors"] = "github.com/mateothegreat/go-config/errors"
}

// createImportDecl creates the import declaration
func (g *ASTCodeGenerator) createImportDecl() ast.Decl {
	specs := make([]ast.Spec, 0, len(g.imports))

	for alias, path := range g.imports {
		spec := &ast.ImportSpec{
			Path: &ast.BasicLit{
				Kind:  token.STRING,
				Value: fmt.Sprintf(`"%s"`, path),
			},
		}
		if alias != "" && alias != path[strings.LastIndex(path, "/")+1:] {
			spec.Name = ast.NewIdent(alias)
		}
		specs = append(specs, spec)
	}

	return &ast.GenDecl{
		Tok:   token.IMPORT,
		Specs: specs,
	}
}

// createInitFunction creates the init function that registers validators
func (g *ASTCodeGenerator) createInitFunction(structs []scanner.StructInfo) ast.Decl {
	stmts := make([]ast.Stmt, 0)

	// Add comment
	comments := &ast.CommentGroup{
		List: []*ast.Comment{
			{Text: "// init registers generated validators with the go-validation registry"},
		},
	}

	// Register each struct's validator
	for _, structInfo := range structs {
		stmt := g.createValidatorRegistration(structInfo.Name)
		stmts = append(stmts, stmt)
	}

	return &ast.FuncDecl{
		Doc:  comments,
		Name: ast.NewIdent("init"),
		Type: &ast.FuncType{
			Params: &ast.FieldList{},
		},
		Body: &ast.BlockStmt{
			List: stmts,
		},
	}
}

// createValidatorRegistration creates a validator registration statement
func (g *ASTCodeGenerator) createValidatorRegistration(structName string) ast.Stmt {
	// validation.RegisterValidation(structName, ValidateStructName)
	return &ast.ExprStmt{
		X: &ast.CallExpr{
			Fun: &ast.SelectorExpr{
				X:   ast.NewIdent("validation"),
				Sel: ast.NewIdent("RegisterValidation"),
			},
			Args: []ast.Expr{
				&ast.BasicLit{
					Kind:  token.STRING,
					Value: fmt.Sprintf(`"%s"`, strings.ToLower(structName)),
				},
				ast.NewIdent(fmt.Sprintf("Validate%s", structName)),
			},
		},
	}
}

// createValidationMethod creates a validation method for a struct
func (g *ASTCodeGenerator) createValidationMethod(structInfo scanner.StructInfo) (ast.Decl, error) {
	// Create method receiver
	recv := &ast.FieldList{
		List: []*ast.Field{
			{
				Names: []*ast.Ident{ast.NewIdent("s")},
				Type: &ast.StarExpr{
					X: ast.NewIdent(structInfo.Name),
				},
			},
		},
	}

	// Create method body
	body, err := g.createValidationBody(structInfo)
	if err != nil {
		return nil, err
	}

	// Create the method declaration
	return &ast.FuncDecl{
		Doc: &ast.CommentGroup{
			List: []*ast.Comment{
				{Text: fmt.Sprintf("// Validate validates the %s struct using zero-reflection validation", structInfo.Name)},
			},
		},
		Recv: recv,
		Name: ast.NewIdent("Validate"),
		Type: &ast.FuncType{
			Params: &ast.FieldList{},
			Results: &ast.FieldList{
				List: []*ast.Field{
					{Type: ast.NewIdent("error")},
				},
			},
		},
		Body: body,
	}, nil
}

// createValidationBody creates the validation method body
func (g *ASTCodeGenerator) createValidationBody(structInfo scanner.StructInfo) (*ast.BlockStmt, error) {
	stmts := make([]ast.Stmt, 0)

	// Create error builder variable
	stmts = append(stmts, &ast.DeclStmt{
		Decl: &ast.GenDecl{
			Tok: token.VAR,
			Specs: []ast.Spec{
				&ast.ValueSpec{
					Names: []*ast.Ident{ast.NewIdent("errs")},
					Type:  ast.NewIdent("*errors.FluentError"),
					Values: []ast.Expr{
						&ast.CallExpr{
							Fun: &ast.SelectorExpr{
								X:   ast.NewIdent("errors"),
								Sel: ast.NewIdent("NewError"),
							},
						},
					},
				},
			},
		},
	})

	// Generate validation for each field
	for _, field := range structInfo.Fields {
		if len(field.ValidateRules) == 0 {
			continue
		}

		fieldStmts, err := g.createFieldValidation(field)
		if err != nil {
			return nil, fmt.Errorf("failed to create validation for field %s: %w", field.Name, err)
		}
		stmts = append(stmts, fieldStmts...)
	}

	// Add return statement
	stmts = append(stmts, &ast.IfStmt{
		Cond: &ast.CallExpr{
			Fun: &ast.SelectorExpr{
				X:   ast.NewIdent("errs"),
				Sel: ast.NewIdent("HasErrors"),
			},
		},
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				&ast.ReturnStmt{
					Results: []ast.Expr{ast.NewIdent("errs")},
				},
			},
		},
	})

	stmts = append(stmts, &ast.ReturnStmt{
		Results: []ast.Expr{ast.NewIdent("nil")},
	})

	return &ast.BlockStmt{List: stmts}, nil
}

// createFieldValidation creates validation statements for a field
func (g *ASTCodeGenerator) createFieldValidation(field scanner.FieldInfo) ([]ast.Stmt, error) {
	stmts := make([]ast.Stmt, 0)

	// Add comment for field
	comment := &ast.CommentGroup{
		List: []*ast.Comment{
			{Text: fmt.Sprintf("// Validate %s", field.Name)},
		},
	}

	// Process each validation rule
	for rule, value := range field.ValidateRules {
		validatorExpr := g.getValidatorExpression(rule, value, field.Type)
		if validatorExpr == nil {
			continue
		}

		// Create validation call - adapt based on validator type
		var callExpr ast.Expr

		// For simple validators that just need the field value
		if info, exists := g.registry.validators[rule]; exists && !info.RequiresArgs {
			// Direct call with field value
			callExpr = &ast.CallExpr{
				Fun: validatorExpr,
				Args: []ast.Expr{
					&ast.SelectorExpr{
						X:   ast.NewIdent("s"),
						Sel: ast.NewIdent(field.Name),
					},
				},
			}
		} else {
			// For validators that return a function (like Min, Max, etc.)
			// They are called as: rules.Min(10)(value)
			callExpr = &ast.CallExpr{
				Fun: validatorExpr,
				Args: []ast.Expr{
					&ast.SelectorExpr{
						X:   ast.NewIdent("s"),
						Sel: ast.NewIdent(field.Name),
					},
				},
			}
		}

		// Create if statement for validation
		stmt := &ast.IfStmt{
			Cond: &ast.UnaryExpr{
				Op: token.NOT,
				X:  callExpr,
			},
			Body: &ast.BlockStmt{
				List: []ast.Stmt{
					g.createErrorStatement(field.Name, rule, value),
				},
			},
		}

		stmts = append(stmts, stmt)
	}

	if len(stmts) > 0 && comment != nil {
		// Attach comment to first statement
		stmts[0].(*ast.IfStmt).If = 1 // Dummy position to attach comment
	}

	return stmts, nil
}

// getValidatorExpression returns the validator function expression for a rule
func (g *ASTCodeGenerator) getValidatorExpression(rule, value string, fieldType string) ast.Expr {
	// Check if we have a cached validator
	cacheKey := fmt.Sprintf("%s_%s", rule, value)
	if expr, ok := g.validators[cacheKey]; ok {
		return expr
	}

	// Get validator expression from registry
	expr := g.registry.GetValidatorExpression(rule, value, fieldType)

	// Cache the expression
	g.validators[cacheKey] = expr
	return expr
}

// createErrorStatement creates an error statement for a validation failure
func (g *ASTCodeGenerator) createErrorStatement(fieldName, rule, value string) ast.Stmt {
	// errs.Field(fieldName).RuleSpecificError()
	fieldCall := &ast.CallExpr{
		Fun: &ast.SelectorExpr{
			X:   ast.NewIdent("errs"),
			Sel: ast.NewIdent("Field"),
		},
		Args: []ast.Expr{
			&ast.BasicLit{
				Kind:  token.STRING,
				Value: fmt.Sprintf(`"%s"`, fieldName),
			},
		},
	}

	// Choose appropriate error method based on rule
	var errorMethod string
	switch rule {
	case "required":
		errorMethod = "Required"
	case "email":
		errorMethod = "Email"
	case "url":
		errorMethod = "URL"
	case "min":
		return &ast.ExprStmt{
			X: &ast.CallExpr{
				Fun: &ast.SelectorExpr{
					X:   fieldCall,
					Sel: ast.NewIdent("Min"),
				},
				Args: []ast.Expr{
					&ast.BasicLit{
						Kind:  token.INT,
						Value: value,
					},
				},
			},
		}
	case "max":
		return &ast.ExprStmt{
			X: &ast.CallExpr{
				Fun: &ast.SelectorExpr{
					X:   fieldCall,
					Sel: ast.NewIdent("Max"),
				},
				Args: []ast.Expr{
					&ast.BasicLit{
						Kind:  token.INT,
						Value: value,
					},
				},
			},
		}
	case "minlen":
		return &ast.ExprStmt{
			X: &ast.CallExpr{
				Fun: &ast.SelectorExpr{
					X:   fieldCall,
					Sel: ast.NewIdent("MinLength"),
				},
				Args: []ast.Expr{
					&ast.BasicLit{
						Kind:  token.INT,
						Value: value,
					},
				},
			},
		}
	case "maxlen":
		return &ast.ExprStmt{
			X: &ast.CallExpr{
				Fun: &ast.SelectorExpr{
					X:   fieldCall,
					Sel: ast.NewIdent("MaxLength"),
				},
				Args: []ast.Expr{
					&ast.BasicLit{
						Kind:  token.INT,
						Value: value,
					},
				},
			},
		}
	default:
		errorMethod = "Format"
	}

	if errorMethod == "Format" {
		return &ast.ExprStmt{
			X: &ast.CallExpr{
				Fun: &ast.SelectorExpr{
					X:   fieldCall,
					Sel: ast.NewIdent(errorMethod),
				},
				Args: []ast.Expr{
					&ast.BasicLit{
						Kind:  token.STRING,
						Value: fmt.Sprintf(`"validation failed for rule: %s"`, rule),
					},
				},
			},
		}
	}

	return &ast.ExprStmt{
		X: &ast.CallExpr{
			Fun: &ast.SelectorExpr{
				X:   fieldCall,
				Sel: ast.NewIdent(errorMethod),
			},
		},
	}
}

// createStandaloneValidator creates a standalone validator function for registry
func (g *ASTCodeGenerator) createStandaloneValidator(structInfo scanner.StructInfo) (ast.Decl, error) {
	// Create function name
	funcName := fmt.Sprintf("Validate%s", structInfo.Name)

	// Create function body
	body, err := g.createStandaloneValidatorBody(structInfo)
	if err != nil {
		return nil, err
	}

	// Create the function declaration
	return &ast.FuncDecl{
		Doc: &ast.CommentGroup{
			List: []*ast.Comment{
				{Text: fmt.Sprintf("// %s validates %s instances for use with go-validation registry", funcName, structInfo.Name)},
			},
		},
		Name: ast.NewIdent(funcName),
		Type: &ast.FuncType{
			Params: &ast.FieldList{
				List: []*ast.Field{
					{
						Names: []*ast.Ident{ast.NewIdent("fl")},
						Type: &ast.SelectorExpr{
							X:   ast.NewIdent("validation"),
							Sel: ast.NewIdent("FieldLevel"),
						},
					},
				},
			},
			Results: &ast.FieldList{
				List: []*ast.Field{
					{Type: ast.NewIdent("bool")},
				},
			},
		},
		Body: body,
	}, nil
}

// createStandaloneValidatorBody creates the body for a standalone validator
func (g *ASTCodeGenerator) createStandaloneValidatorBody(structInfo scanner.StructInfo) (*ast.BlockStmt, error) {
	stmts := []ast.Stmt{
		// Get the field interface value
		&ast.AssignStmt{
			Lhs: []ast.Expr{ast.NewIdent("value")},
			Tok: token.DEFINE,
			Rhs: []ast.Expr{
				&ast.CallExpr{
					Fun: &ast.SelectorExpr{
						X:   ast.NewIdent("fl"),
						Sel: ast.NewIdent("Field"),
					},
				},
			},
		},
		// Get the reflect.Value
		&ast.AssignStmt{
			Lhs: []ast.Expr{ast.NewIdent("v")},
			Tok: token.DEFINE,
			Rhs: []ast.Expr{
				&ast.CallExpr{
					Fun: &ast.SelectorExpr{
						X:   ast.NewIdent("value"),
						Sel: ast.NewIdent("Interface"),
					},
				},
			},
		},
		// Type assertion to our struct
		&ast.AssignStmt{
			Lhs: []ast.Expr{
				ast.NewIdent("s"),
				ast.NewIdent("ok"),
			},
			Tok: token.DEFINE,
			Rhs: []ast.Expr{
				&ast.TypeAssertExpr{
					X: ast.NewIdent("v"),
					Type: &ast.StarExpr{
						X: ast.NewIdent(structInfo.Name),
					},
				},
			},
		},
		// Check type assertion
		&ast.IfStmt{
			Cond: &ast.UnaryExpr{
				Op: token.NOT,
				X:  ast.NewIdent("ok"),
			},
			Body: &ast.BlockStmt{
				List: []ast.Stmt{
					// Try non-pointer type
					&ast.AssignStmt{
						Lhs: []ast.Expr{
							ast.NewIdent("s2"),
							ast.NewIdent("ok2"),
						},
						Tok: token.DEFINE,
						Rhs: []ast.Expr{
							&ast.TypeAssertExpr{
								X:    ast.NewIdent("v"),
								Type: ast.NewIdent(structInfo.Name),
							},
						},
					},
					&ast.IfStmt{
						Cond: &ast.UnaryExpr{
							Op: token.NOT,
							X:  ast.NewIdent("ok2"),
						},
						Body: &ast.BlockStmt{
							List: []ast.Stmt{
								&ast.ReturnStmt{
									Results: []ast.Expr{ast.NewIdent("false")},
								},
							},
						},
					},
					// Convert to pointer
					&ast.AssignStmt{
						Lhs: []ast.Expr{ast.NewIdent("s")},
						Tok: token.ASSIGN,
						Rhs: []ast.Expr{
							&ast.UnaryExpr{
								Op: token.AND,
								X:  ast.NewIdent("s2"),
							},
						},
					},
				},
			},
		},
		// Call validation method
		&ast.ReturnStmt{
			Results: []ast.Expr{
				&ast.BinaryExpr{
					X: &ast.CallExpr{
						Fun: &ast.SelectorExpr{
							X:   ast.NewIdent("s"),
							Sel: ast.NewIdent("Validate"),
						},
					},
					Op: token.EQL,
					Y:  ast.NewIdent("nil"),
				},
			},
		},
	}

	return &ast.BlockStmt{List: stmts}, nil
}
