package generator

// validationTemplate is the template for generating validation methods
const validationTemplate = `
{{- $struct := index .Structs 0}}
// Validate validates the {{$struct.Name}} struct using zero-reflection validation
func (s *{{$struct.Name}}) Validate() error {
{{- range $field := $struct.Fields}}
{{- if $field.ValidateRules}}
{{- range $rule, $value := $field.ValidateRules}}
	{{buildValidator $field $rule $value}}
{{- end}}
{{- end}}
{{- end}}
	return nil
}`

// fileTemplate is the template for generating complete validation files
const fileTemplate = `// Code generated by go-validate. DO NOT EDIT.
// This file contains zero-reflection validation methods.
// Generated at: {{.Timestamp}}

package {{.PackageName}}

import (
{{- range .Imports}}
	"{{.}}"
{{- end}}
)

// Pre-compiled regex patterns for validation performance
var (
	emailRegex     = regexp.MustCompile(` + "`^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$`" + `)
	urlRegex       = regexp.MustCompile(` + "`^[a-zA-Z][a-zA-Z0-9+.-]*://[^\\s]*$`" + `)
	alphaRegex     = regexp.MustCompile(` + "`^[a-zA-Z]+$`" + `)
	alphaNumRegex  = regexp.MustCompile(` + "`^[a-zA-Z0-9]+$`" + `)
	numericRegex   = regexp.MustCompile(` + "`^[0-9]+$`" + `)
)

// Auto-generated validator registration  
func init() {
{{range .Structs}}
	// Register {{.Name}} for both pointer and value types
	validate.RegisterGeneratedValidator("{{.Name}}", func(data any) error {
		switch v := data.(type) {
		case *{{.Name}}:
			return v.Validate()
		case {{.Name}}:
			return v.Validate()
		default:
			return fmt.Errorf("expected {{.Name}} or *{{.Name}}, got %T", data)
		}
	})
{{end}}
}

{{range .Structs}}
// Validate validates the {{.Name}} struct using zero-reflection validation
func (s *{{.Name}}) Validate() error {
{{- range $field := .Fields}}
{{- if $field.ValidateRules}}
{{- range $rule, $value := $field.ValidateRules}}
	{{buildValidator $field $rule $value}}
{{- end}}
{{- end}}
{{- end}}
	return nil
}

{{end}}`
