package goconfig

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/mateothegreat/go-config/internal/generator"
	"github.com/mateothegreat/go-config/internal/errors"
)

// IntegrationTestConfig represents a test configuration for integration testing
type IntegrationTestConfig struct {
	// Service name
	Name string `json:"name" validate:"required,minlen=3,maxlen=50" yaml:"name"`
	
	// Service port
	Port int `json:"port" validate:"min=1,max=65535" yaml:"port"`
	
	// Database URL
	DatabaseURL string `json:"database_url" validate:"required,url" yaml:"database_url"`
	
	// Admin email
	AdminEmail string `json:"admin_email" validate:"required,email" yaml:"admin_email"`
	
	// Debug mode
	Debug bool `json:"debug" yaml:"debug"`
	
	// API timeout in seconds
	Timeout float64 `json:"timeout" validate:"min=0.1,max=300" yaml:"timeout"`
	
	// Allowed origins for CORS
	AllowedOrigins []string `json:"allowed_origins" yaml:"allowed_origins"`
	
	// Feature flags
	Features map[string]bool `json:"features" yaml:"features"`
}

func TestIntegrationEndToEnd(t *testing.T) {
	// This integration test validates the end-to-end functionality
	
	// Test configuration
	config := IntegrationTestConfig{
		Name:        "test-service",
		Port:        8080,
		DatabaseURL: "postgres://localhost:5432/test",
		AdminEmail:  "admin@example.com",
		Debug:       true,
		Timeout:     30.0,
		AllowedOrigins: []string{"http://localhost:3000"},
		Features: map[string]bool{
			"auth":    true,
			"metrics": false,
		},
	}

	// Test that the configuration is valid
	t.Run("ConfigValidation", func(t *testing.T) {
		validator := NewStructValidator()
		err := validator.Validate(&config)
		assert.NoError(t, err)
	})
	
	// Test invalid configuration
	t.Run("InvalidConfigValidation", func(t *testing.T) {
		invalidConfig := IntegrationTestConfig{
			Name:        "ab", // Too short
			Port:        70000, // Too high
			DatabaseURL: "not-a-url",
			AdminEmail:  "not-an-email",
			Timeout:     -1.0, // Negative
		}
		
		validator := NewStructValidator()
		err := validator.Validate(&invalidConfig)
		assert.Error(t, err)
		
		// Check that it's a ValidationErrors type
		validationErr, ok := err.(ValidationErrors)
		assert.True(t, ok)
		assert.True(t, len(validationErr) > 0)
	})
}

func TestCodeGeneration(t *testing.T) {
	tempDir := t.TempDir()
	
	// Create a test Go file with validation tags
	testGoContent := `package test

// TestGeneratedConfig is a test config for code generation
type TestGeneratedConfig struct {
	Name  string ` + "`" + `validate:"required,minlen=3"` + "`" + `
	Email string ` + "`" + `validate:"required,email"` + "`" + `
	Port  int    ` + "`" + `validate:"min=1,max=65535"` + "`" + `
}
`
	
	inputFile := filepath.Join(tempDir, "config.go")
	err := os.WriteFile(inputFile, []byte(testGoContent), 0644)
	require.NoError(t, err)
	
	// Generate validation code
	gen := generator.NewGenerator(
		generator.WithInputDir(tempDir),
		generator.WithOutputDir(tempDir),
		generator.WithPackage("test"),
		generator.WithVerbose(false),
	)
	
	err = gen.Generate()
	require.NoError(t, err)
	
	// Check that generated file exists
	generatedFile := filepath.Join(tempDir, "validation_generated.go")
	_, err = os.Stat(generatedFile)
	assert.NoError(t, err)
	
	// Read and verify generated content
	content, err := os.ReadFile(generatedFile)
	require.NoError(t, err)
	
	contentStr := string(content)
	assert.Contains(t, contentStr, "package test")
	assert.Contains(t, contentStr, "func (s *TestGeneratedConfig) Validate() error")
	assert.Contains(t, contentStr, "Code generated by go-validate")
	assert.Contains(t, contentStr, "emailRegex")
}

func TestFluentErrorComposition(t *testing.T) {
	// Test fluent error building
	err := errors.NewError().
		Field("name").Required().
		Field("email").Format("must be a valid email address").
		Field("port").Range(1, 65535)
	
	assert.True(t, err.HasErrors())
	errorList := err.Errors()
	assert.Len(t, errorList, 3)
	
	// Check individual errors
	assert.Equal(t, "name", errorList[0].Field)
	assert.Contains(t, errorList[0].Message, "required")
	
	assert.Equal(t, "email", errorList[1].Field)
	assert.Contains(t, errorList[1].Message, "valid email")
	
	assert.Equal(t, "port", errorList[2].Field)
	assert.Contains(t, errorList[2].Message, "between 1 and 65535")
}

func TestMultiError(t *testing.T) {
	fieldErrors := map[string]error{
		"name":  errors.NewError().Field("name").Required(),
		"email": errors.NewError().Field("email").Format("invalid email"),
		"port":  errors.NewError().Field("port").Format("out of range"),
	}
	
	multiErr := errors.NewMultiError(fieldErrors)
	
	assert.True(t, multiErr.HasErrors())
	assert.Len(t, multiErr.Errors(), 3)
	
	// Test individual field access
	assert.NotNil(t, multiErr.Get("name"))
	assert.NotNil(t, multiErr.Get("email"))
	assert.NotNil(t, multiErr.Get("port"))
	assert.Nil(t, multiErr.Get("nonexistent"))
	
	// Test error message
	errMsg := multiErr.Error()
	assert.Contains(t, errMsg, "name:")
	assert.Contains(t, errMsg, "email:")
	assert.Contains(t, errMsg, "port:")
}

func TestValidationPerformance(t *testing.T) {
	config := IntegrationTestConfig{
		Name:        "performance-test",
		Port:        8080,
		DatabaseURL: "https://example.com/db",
		AdminEmail:  "admin@example.com",
		Debug:       false,
		Timeout:     15.0,
	}
	
	// Test traditional validator performance
	validator := NewStructValidator()
	
	t.Run("TraditionalValidator", func(t *testing.T) {
		for i := 0; i < 1000; i++ {
			err := validator.Validate(&config)
			assert.NoError(t, err)
		}
	})
	
	// Test fast validator performance
	fastValidator := NewFastStructValidator()
	
	t.Run("FastValidator", func(t *testing.T) {
		for i := 0; i < 1000; i++ {
			err := fastValidator.Validate(&config)
			assert.NoError(t, err)
		}
	})
}

func BenchmarkValidationComparison(b *testing.B) {
	config := IntegrationTestConfig{
		Name:        "benchmark-test",
		Port:        8080,
		DatabaseURL: "https://example.com/db",
		AdminEmail:  "admin@example.com",
		Debug:       false,
		Timeout:     15.0,
		AllowedOrigins: []string{"http://localhost:3000", "https://app.example.com"},
		Features: map[string]bool{
			"auth":      true,
			"metrics":   true,
			"analytics": false,
		},
	}
	
	b.Run("TraditionalValidator", func(b *testing.B) {
		validator := NewStructValidator()
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			_ = validator.Validate(&config)
		}
	})
	
	b.Run("FastValidator", func(b *testing.B) {
		validator := NewFastStructValidator()
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			_ = validator.Validate(&config)
		}
	})
	
	b.Run("FluentErrorBuilding", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			_ = errors.NewError().
				Field("name").Required().
				Field("email").Format("invalid").
				Field("port").Range(1, 65535)
		}
	})
}

func BenchmarkMemoryAllocation(b *testing.B) {
	config := IntegrationTestConfig{
		Name:        "memory-test",
		Port:        8080,
		DatabaseURL: "https://example.com/db",
		AdminEmail:  "admin@example.com",
		Debug:       false,
		Timeout:     15.0,
	}
	
	b.Run("ZeroAllocationPath", func(b *testing.B) {
		validator := NewFastStructValidator()
		b.ReportAllocs()
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			_ = validator.Validate(&config)
		}
	})
}