// Code generated by go-config. DO NOT EDIT.
// This file contains zero-reflection validation methods.

package main

import (
	"github.com/mateothegreat/go-config/validation"
)

// Generated validator for ServerConfig - zero reflection, maximum performance
func (c *ServerConfig) Validate() validation.ValidationErrors {
	var errors validation.ValidationErrors

	// Validate Name
	if !validation.IsRequired(c.Name) {
		errors |= validation.ErrRequired
	}
	if !validation.HasMinLength(c.Name, 3) {
		errors |= validation.ErrMinLength
	}
	if !validation.HasMaxLength(c.Name, 50) {
		errors |= validation.ErrMaxLength
	}

	// Validate Environment
	if !validation.IsRequired(c.Environment) {
		errors |= validation.ErrRequired
	}
	if !validation.IsOneOfString(c.Environment, []string{"dev", "staging", "prod"}) {
		errors |= validation.ErrOneOf
	}

	// Validate Host
	if !validation.IsRequired(c.Host) {
		errors |= validation.ErrRequired
	}
	if c.Host != "" && !validation.IsHostname(c.Host) {
		errors |= validation.ErrHostname
	}

	// Validate Port
	if !validation.IsRequiredInt(c.Port) {
		errors |= validation.ErrRequired
	}
	if !validation.HasMinInt(c.Port, 1) {
		errors |= validation.ErrMin
	}
	if !validation.HasMaxInt(c.Port, 65535) {
		errors |= validation.ErrMax
	}

	// Validate Email
	if !validation.IsRequired(c.Email) {
		errors |= validation.ErrRequired
	}
	if c.Email != "" && !validation.IsEmail(c.Email) {
		errors |= validation.ErrEmail
	}

	// Validate AdminEmails
	if !validation.IsRequiredSlice(c.AdminEmails) {
		errors |= validation.ErrRequired
	}
	if !validation.HasMinSliceLength(c.AdminEmails, 1) {
		errors |= validation.ErrMin
	}
	// Validate each email in AdminEmails slice
	for _, email := range c.AdminEmails {
		if email != "" && !validation.IsEmail(email) {
			errors |= validation.ErrEmail
			break // Stop on first error for performance
		}
	}

	// Validate Debug
	if !validation.IsRequiredBool(c.Debug) {
		errors |= validation.ErrRequired
	}

	return errors
}

// ValidateWithResult validates ServerConfig and returns detailed results
func (c *ServerConfig) ValidateWithResult() *validation.ValidationResult {
	result := validation.NewValidationResult()

	// Validate Name with detailed results
	if !validation.IsRequired(c.Name) {
		result.AddFieldError("Name", validation.ErrRequired)
	}
	if !validation.HasMinLength(c.Name, 3) {
		result.AddFieldError("Name", validation.ErrMinLength)
	}
	if !validation.HasMaxLength(c.Name, 50) {
		result.AddFieldError("Name", validation.ErrMaxLength)
	}

	// Validate Environment with detailed results
	if !validation.IsRequired(c.Environment) {
		result.AddFieldError("Environment", validation.ErrRequired)
	}
	if !validation.IsOneOfString(c.Environment, []string{"dev", "staging", "prod"}) {
		result.AddFieldError("Environment", validation.ErrOneOf)
	}

	// Validate Host with detailed results
	if !validation.IsRequired(c.Host) {
		result.AddFieldError("Host", validation.ErrRequired)
	}
	if c.Host != "" && !validation.IsHostname(c.Host) {
		result.AddFieldError("Host", validation.ErrHostname)
	}

	// Validate Port with detailed results
	if !validation.IsRequiredInt(c.Port) {
		result.AddFieldError("Port", validation.ErrRequired)
	}
	if !validation.HasMinInt(c.Port, 1) {
		result.AddFieldError("Port", validation.ErrMin)
	}
	if !validation.HasMaxInt(c.Port, 65535) {
		result.AddFieldError("Port", validation.ErrMax)
	}

	// Validate Email with detailed results
	if !validation.IsRequired(c.Email) {
		result.AddFieldError("Email", validation.ErrRequired)
	}
	if c.Email != "" && !validation.IsEmail(c.Email) {
		result.AddFieldError("Email", validation.ErrEmail)
	}

	// Validate AdminEmails with detailed results
	if !validation.IsRequiredSlice(c.AdminEmails) {
		result.AddFieldError("AdminEmails", validation.ErrRequired)
	}
	if !validation.HasMinSliceLength(c.AdminEmails, 1) {
		result.AddFieldError("AdminEmails", validation.ErrMin)
	}

	return result
}

// Generated validator for DatabaseConfig - zero reflection, maximum performance
func (c *DatabaseConfig) Validate() validation.ValidationErrors {
	var errors validation.ValidationErrors

	// Validate Driver
	if !validation.IsRequired(c.Driver) {
		errors |= validation.ErrRequired
	}
	if !validation.IsOneOfString(c.Driver, []string{"postgres", "mysql", "sqlite"}) {
		errors |= validation.ErrOneOf
	}

	// Validate Host
	if !validation.IsRequired(c.Host) {
		errors |= validation.ErrRequired
	}
	if c.Host != "" && !validation.IsHostname(c.Host) {
		errors |= validation.ErrHostname
	}

	// Validate Port
	if !validation.IsRequiredInt(c.Port) {
		errors |= validation.ErrRequired
	}
	if !validation.HasMinInt(c.Port, 1) {
		errors |= validation.ErrMin
	}
	if !validation.HasMaxInt(c.Port, 65535) {
		errors |= validation.ErrMax
	}

	// Validate Username
	if !validation.IsRequired(c.Username) {
		errors |= validation.ErrRequired
	}

	// Validate Password
	if !validation.IsRequired(c.Password) {
		errors |= validation.ErrRequired
	}

	// Validate Database
	if !validation.IsRequired(c.Database) {
		errors |= validation.ErrRequired
	}

	// Validate MaxOpenConns
	if !validation.HasMinInt(c.MaxOpenConns, 1) {
		errors |= validation.ErrMin
	}
	if !validation.HasMaxInt(c.MaxOpenConns, 100) {
		errors |= validation.ErrMax
	}

	// Validate MaxIdleConns
	if !validation.HasMinInt(c.MaxIdleConns, 0) {
		errors |= validation.ErrMin
	}
	if !validation.HasMaxInt(c.MaxIdleConns, 100) {
		errors |= validation.ErrMax
	}

	return errors
}

// ValidateWithResult validates DatabaseConfig and returns detailed results
func (c *DatabaseConfig) ValidateWithResult() *validation.ValidationResult {
	result := validation.NewValidationResult()

	// Validate Driver with detailed results
	if !validation.IsRequired(c.Driver) {
		result.AddFieldError("Driver", validation.ErrRequired)
	}
	if !validation.IsOneOfString(c.Driver, []string{"postgres", "mysql", "sqlite"}) {
		result.AddFieldError("Driver", validation.ErrOneOf)
	}

	// Validate Host with detailed results
	if !validation.IsRequired(c.Host) {
		result.AddFieldError("Host", validation.ErrRequired)
	}
	if c.Host != "" && !validation.IsHostname(c.Host) {
		result.AddFieldError("Host", validation.ErrHostname)
	}

	// Validate Port with detailed results
	if !validation.IsRequiredInt(c.Port) {
		result.AddFieldError("Port", validation.ErrRequired)
	}
	if !validation.HasMinInt(c.Port, 1) {
		result.AddFieldError("Port", validation.ErrMin)
	}
	if !validation.HasMaxInt(c.Port, 65535) {
		result.AddFieldError("Port", validation.ErrMax)
	}

	return result
}

// Generated validator for APIConfig - zero reflection, maximum performance
func (c *APIConfig) Validate() validation.ValidationErrors {
	var errors validation.ValidationErrors

	// Validate BaseURL
	if !validation.IsRequired(c.BaseURL) {
		errors |= validation.ErrRequired
	}
	if c.BaseURL != "" && !validation.IsURL(c.BaseURL) {
		errors |= validation.ErrURL
	}

	// Validate APIKey
	if !validation.IsRequired(c.APIKey) {
		errors |= validation.ErrRequired
	}
	if c.APIKey != "" && !validation.IsBase64(c.APIKey) {
		errors |= validation.ErrBase64
	}

	// Validate Version
	if !validation.IsRequired(c.Version) {
		errors |= validation.ErrRequired
	}

	// Validate Timeout
	if !validation.HasMinFloat32(c.Timeout, 0.1) {
		errors |= validation.ErrMin
	}
	if !validation.HasMaxFloat32(c.Timeout, 300) {
		errors |= validation.ErrMax
	}

	// Validate RateLimit
	if !validation.HasMinInt(c.RateLimit, 1) {
		errors |= validation.ErrMin
	}
	if !validation.HasMaxInt(c.RateLimit, 10000) {
		errors |= validation.ErrMax
	}

	return errors
}

// ValidateWithResult validates APIConfig and returns detailed results
func (c *APIConfig) ValidateWithResult() *validation.ValidationResult {
	result := validation.NewValidationResult()

	// Validate BaseURL with detailed results
	if !validation.IsRequired(c.BaseURL) {
		result.AddFieldError("BaseURL", validation.ErrRequired)
	}
	if c.BaseURL != "" && !validation.IsURL(c.BaseURL) {
		result.AddFieldError("BaseURL", validation.ErrURL)
	}

	// Validate APIKey with detailed results
	if !validation.IsRequired(c.APIKey) {
		result.AddFieldError("APIKey", validation.ErrRequired)
	}
	if c.APIKey != "" && !validation.IsBase64(c.APIKey) {
		result.AddFieldError("APIKey", validation.ErrBase64)
	}

	// Validate Version with detailed results
	if !validation.IsRequired(c.Version) {
		result.AddFieldError("Version", validation.ErrRequired)
	}

	return result
}

// Generated validator for Config - zero reflection, maximum performance
func (c *Config) Validate() validation.ValidationErrors {
	var errors validation.ValidationErrors

	// Validate nested Server struct
	serverErrors := c.Server.Validate()
	if serverErrors.HasErrors() {
		errors |= serverErrors
	}

	// Validate nested Database struct
	dbErrors := c.Database.Validate()
	if dbErrors.HasErrors() {
		errors |= dbErrors
	}

	// Validate nested API struct
	apiErrors := c.API.Validate()
	if apiErrors.HasErrors() {
		errors |= apiErrors
	}

	// Validate LogLevel
	if c.LogLevel != "" && !validation.IsOneOfString(c.LogLevel, []string{"debug", "info", "warn", "error"}) {
		errors |= validation.ErrOneOf
	}

	return errors
}

// ValidateWithResult validates Config and returns detailed results
func (c *Config) ValidateWithResult() *validation.ValidationResult {
	result := validation.NewValidationResult()

	// Validate nested Server struct with detailed results
	serverResult := c.Server.ValidateWithResult()
	if serverResult.HasErrors() {
		for field, errs := range serverResult.Fields {
			result.AddFieldError("Server."+field, errs)
		}
	}

	// Validate nested Database struct with detailed results
	dbResult := c.Database.ValidateWithResult()
	if dbResult.HasErrors() {
		for field, errs := range dbResult.Fields {
			result.AddFieldError("Database."+field, errs)
		}
	}

	// Validate nested API struct with detailed results
	apiResult := c.API.ValidateWithResult()
	if apiResult.HasErrors() {
		for field, errs := range apiResult.Fields {
			result.AddFieldError("API."+field, errs)
		}
	}

	// Validate LogLevel with detailed results
	if c.LogLevel != "" && !validation.IsOneOfString(c.LogLevel, []string{"debug", "info", "warn", "error"}) {
		result.AddFieldError("LogLevel", validation.ErrOneOf)
	}

	return result
}