package generator

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mateothegreat/go-config/internal/scanner"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestNewGenerator(t *testing.T) {
	tests := []struct {
		name     string
		options  []GeneratorOption
		expected GeneratorConfig
	}{
		{
			name:    "default config",
			options: nil,
			expected: GeneratorConfig{
				InputDir:    ".",
				OutputDir:   ".",
				PackageName: "",
				DryRun:      false,
				Multi:       false,
				Cache:       false,
				Verbose:     false,
			},
		},
		{
			name: "with custom options",
			options: []GeneratorOption{
				WithInputDir("./src"),
				WithOutputDir("./generated"),
				WithPackage("mypackage"),
				WithStructs("Config", "Settings"),
				WithDryRun(true),
				WithMulti(true),
				WithCache(true),
				WithVerbose(true),
			},
			expected: GeneratorConfig{
				InputDir:    "./src",
				OutputDir:   "./generated",
				PackageName: "mypackage",
				Structs:     []string{"Config", "Settings"},
				DryRun:      true,
				Multi:       true,
				Cache:       true,
				Verbose:     true,
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			gen := NewGenerator(tt.options...)
			assert.Equal(t, tt.expected.InputDir, gen.config.InputDir)
			assert.Equal(t, tt.expected.OutputDir, gen.config.OutputDir)
			assert.Equal(t, tt.expected.PackageName, gen.config.PackageName)
			assert.Equal(t, tt.expected.Structs, gen.config.Structs)
			assert.Equal(t, tt.expected.DryRun, gen.config.DryRun)
			assert.Equal(t, tt.expected.Multi, gen.config.Multi)
			assert.Equal(t, tt.expected.Cache, gen.config.Cache)
			assert.Equal(t, tt.expected.Verbose, gen.config.Verbose)
		})
	}
}

func TestGeneratorFilterStructs(t *testing.T) {
	gen := NewGenerator(WithStructs("Config", "Settings"))

	structs := []scanner.StructInfo{
		{Name: "Config"},
		{Name: "Settings"},
		{Name: "Database"},
		{Name: "Server"},
	}

	filtered := gen.filterStructs(structs)

	assert.Len(t, filtered, 2)
	assert.Equal(t, "Config", filtered[0].Name)
	assert.Equal(t, "Settings", filtered[1].Name)
}

func TestGeneratorEnsureOutputDir(t *testing.T) {
	tempDir := t.TempDir()
	outputDir := filepath.Join(tempDir, "output", "nested")

	gen := NewGenerator(WithOutputDir(outputDir))

	err := gen.ensureOutputDir()
	require.NoError(t, err)

	// Check that directory was created
	info, err := os.Stat(outputDir)
	require.NoError(t, err)
	assert.True(t, info.IsDir())
}

func TestGeneratorEnsureOutputDirError(t *testing.T) {
	tempDir := t.TempDir()

	// Create a file instead of directory
	filePath := filepath.Join(tempDir, "notadir")
	err := os.WriteFile(filePath, []byte("test"), 0644)
	require.NoError(t, err)

	gen := NewGenerator(WithOutputDir(filePath))

	err = gen.ensureOutputDir()
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "exists but is not a directory")
}

func TestGenerateSingleFile(t *testing.T) {
	tempDir := t.TempDir()

	structs := []scanner.StructInfo{
		{
			Name:        "TestConfig",
			PackageName: "test",
			Fields: []scanner.FieldInfo{
				{
					Name: "Name",
					Type: "string",
					ValidateRules: map[string]string{
						"required": "",
						"minlen":   "3",
					},
				},
				{
					Name: "Port",
					Type: "int",
					ValidateRules: map[string]string{
						"min": "1",
						"max": "65535",
					},
				},
			},
		},
	}

	gen := NewGenerator(
		WithOutputDir(tempDir),
		WithVerbose(false),
	)

	err := gen.generateSingleFile(structs, "test")
	require.NoError(t, err)

	// Check that file was created
	outputPath := filepath.Join(tempDir, "validation_generated.go")
	content, err := os.ReadFile(outputPath)
	require.NoError(t, err)

	contentStr := string(content)
	assert.Contains(t, contentStr, "package test")
	assert.Contains(t, contentStr, "func (s *TestConfig) Validate() error")
	assert.Contains(t, contentStr, "Code generated by go-validate")
}

func TestGenerateDryRun(t *testing.T) {
	structs := []scanner.StructInfo{
		{
			Name:        "TestConfig",
			PackageName: "test",
			Fields: []scanner.FieldInfo{
				{
					Name: "Name",
					Type: "string",
					ValidateRules: map[string]string{
						"required": "",
					},
				},
			},
		},
	}

	gen := NewGenerator(
		WithDryRun(true),
		WithVerbose(false),
	)

	// Dry run should not create any files
	err := gen.generateSingleFile(structs, "test")
	require.NoError(t, err)
}

func TestGenerateMultipleFiles(t *testing.T) {
	tempDir := t.TempDir()

	structs := []scanner.StructInfo{
		{
			Name:        "ConfigA",
			PackageName: "test",
			Fields: []scanner.FieldInfo{
				{Name: "FieldA", Type: "string", ValidateRules: map[string]string{"required": ""}},
			},
		},
		{
			Name:        "ConfigB",
			PackageName: "test",
			Fields: []scanner.FieldInfo{
				{Name: "FieldB", Type: "int", ValidateRules: map[string]string{"min": "1"}},
			},
		},
	}

	gen := NewGenerator(
		WithOutputDir(tempDir),
		WithMulti(true),
		WithVerbose(false),
	)

	err := gen.generateMultipleFiles(structs, "test")
	require.NoError(t, err)

	// Check that multiple files were created
	files, err := os.ReadDir(tempDir)
	require.NoError(t, err)

	var goFiles []string
	for _, file := range files {
		if strings.HasSuffix(file.Name(), ".go") {
			goFiles = append(goFiles, file.Name())
		}
	}

	assert.Len(t, goFiles, 2)
	assert.Contains(t, goFiles, "configa_validation_generated.go")
	assert.Contains(t, goFiles, "configb_validation_generated.go")
}
