package generator

// validationTemplate is the template for generating validation methods
const validationTemplate = `
// Validate validates the {{.Structs.0.Name}} struct using zero-reflection validation
func (s *{{.Structs.0.Name}}) Validate() error {
{{- range $field := .Structs.0.Fields}}
{{- if $field.ValidateRules}}
{{- range $rule, $value := $field.ValidateRules}}
	{{buildValidator $field $rule $value}}
{{- end}}
{{- end}}
{{- end}}
	return nil
}`

// fileTemplate is the template for generating complete validation files
const fileTemplate = `// Code generated by go-validate. DO NOT EDIT.
// This file contains zero-reflection validation methods.
// Generated at: {{.Timestamp}}

package {{.PackageName}}

import (
{{- range .Imports}}
	"{{.}}"
{{- end}}
)

// Pre-compiled regex patterns for validation performance
var (
	emailRegex     = regexp.MustCompile(` + "`^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$`" + `)
	urlRegex       = regexp.MustCompile(` + "`^[a-zA-Z][a-zA-Z0-9+.-]*://[^\\s]*$`" + `)
	alphaRegex     = regexp.MustCompile(` + "`^[a-zA-Z]+$`" + `)
	alphaNumRegex  = regexp.MustCompile(` + "`^[a-zA-Z0-9]+$`" + `)
	numericRegex   = regexp.MustCompile(` + "`^[0-9]+$`" + `)
)

{{range .Structs}}
// Validate validates the {{.Name}} struct using zero-reflection validation
func (s *{{.Name}}) Validate() error {
{{- range $field := .Fields}}
{{- if $field.ValidateRules}}
{{- range $rule, $value := $field.ValidateRules}}
	{{buildValidator $field $rule $value}}
{{- end}}
{{- end}}
{{- end}}
	return nil
}

{{end}}`

// benchmarkTemplate is the template for generating benchmark tests
const benchmarkTemplate = `// Code generated by go-validate. DO NOT EDIT.
// This file contains benchmark tests for validation methods.
// Generated at: {{.Timestamp}}

package {{.PackageName}}

import (
	"testing"
	"github.com/mateothegreat/go-config"
)

{{range .Structs}}
// Benchmark{{.Name}}Validate benchmarks the generated validation method
func Benchmark{{.Name}}Validate(b *testing.B) {
	config := &{{.Name}}{
{{- range .Fields}}
{{- if eq .Type "string"}}
		{{.Name}}: "test-value",
{{- else if eq .Type "int"}}
		{{.Name}}: 42,
{{- else if eq .Type "bool"}}
		{{.Name}}: true,
{{- else if eq .Type "float64"}}
		{{.Name}}: 3.14,
{{- else}}
		{{.Name}}: {{.Type}}{},
{{- end}}
{{- end}}
	}

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_ = config.Validate()
	}
}

// Benchmark{{.Name}}ValidateReflection benchmarks reflection-based validation
func Benchmark{{.Name}}ValidateReflection(b *testing.B) {
	config := &{{.Name}}{
{{- range .Fields}}
{{- if eq .Type "string"}}
		{{.Name}}: "test-value",
{{- else if eq .Type "int"}}
		{{.Name}}: 42,
{{- else if eq .Type "bool"}}
		{{.Name}}: true,
{{- else if eq .Type "float64"}}
		{{.Name}}: 3.14,
{{- else}}
		{{.Name}}: {{.Type}}{},
{{- end}}
{{- end}}
	}

	validator := goconfig.NewStructValidator()
	
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_ = validator.Validate(config)
	}
}

{{end}}`

// testTemplate is the template for generating test files
const testTemplate = `// Code generated by go-validate. DO NOT EDIT.
// This file contains tests for validation methods.
// Generated at: {{.Timestamp}}

package {{.PackageName}}

import (
	"testing"
	"github.com/stretchr/testify/assert"
	"github.com/mateothegreat/go-config/internal/errors"
)

{{range .Structs}}
func Test{{.Name}}Validate(t *testing.T) {
	tests := []struct {
		name    string
		config  {{.Name}}
		wantErr bool
	}{
		{
			name: "valid config",
			config: {{.Name}}{
{{- range .Fields}}
{{- if eq .Type "string"}}
				{{.Name}}: "valid-value",
{{- else if eq .Type "int"}}
				{{.Name}}: 42,
{{- else if eq .Type "bool"}}
				{{.Name}}: true,
{{- else if eq .Type "float64"}}
				{{.Name}}: 3.14,
{{- end}}
{{- end}}
			},
			wantErr: false,
		},
{{- range .Fields}}
{{- if .Required}}
		{
			name: "missing required field {{.Name}}",
			config: {{$.Name}}{
				// {{.Name}} is missing
{{- range $field := $.Fields}}
{{- if ne $field.Name .Name}}
{{- if eq $field.Type "string"}}
				{{$field.Name}}: "valid-value",
{{- else if eq $field.Type "int"}}
				{{$field.Name}}: 42,
{{- else if eq $field.Type "bool"}}
				{{$field.Name}}: true,
{{- else if eq $field.Type "float64"}}
				{{$field.Name}}: 3.14,
{{- end}}
{{- end}}
{{- end}}
			},
			wantErr: true,
		},
{{- end}}
{{- end}}
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.config.Validate()
			if tt.wantErr {
				assert.Error(t, err)
			} else {
				assert.NoError(t, err)
			}
		})
	}
}

{{end}}`

// pluginTemplate is the template for custom validation plugins
const pluginTemplate = `// Custom validation plugin for {{.Name}}
// Generated at: {{.Timestamp}}

package plugins

import (
{{- range .Imports}}
	"{{.}}"
{{- end}}
)

// {{.Name}}Plugin implements custom validation for {{.Type}}
type {{.Name}}Plugin struct{}

// Validate implements the ValidatorPlugin interface
func (p *{{.Name}}Plugin) Validate(field interface{}) error {
	value, ok := field.({{.Type}})
	if !ok {
		return fmt.Errorf("expected {{.Type}}, got %T", field)
	}

	{{.Function}}
}

// Register{{.Name}} registers the {{.Name}} validation plugin
func Register{{.Name}}() {
	RegisterValidator("{{lower .Name}}", &{{.Name}}Plugin{})
}`