// Code generated by go-config. DO NOT EDIT.
// This file contains zero-reflection validation methods.

package main

import (
	"fmt"
	"regexp"
	"net"
	"net/url"

	validation "github.com/mateothegreat/go-validation"
	"github.com/mateothegreat/go-config/errors"
)

// Validation patterns
var (
	emailRegex = regexp.MustCompile(`^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$`)
	urlRegex = regexp.MustCompile(`^[a-zA-Z][a-zA-Z0-9+.-]*://[^\s]*$`)
	alphaRegex = regexp.MustCompile(`^[a-zA-Z]+$`)
	alphaNumRegex = regexp.MustCompile(`^[a-zA-Z0-9]+$`)
	numericRegex = regexp.MustCompile(`^[0-9]+$`)
	uuidRegex = regexp.MustCompile(`^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`)
	base64Regex = regexp.MustCompile(`^[A-Za-z0-9+/]*={0,2}$`)
)

// Helper validation functions
func isValidEmail(email string) bool {
	return emailRegex.MatchString(email)
}

func isValidURL(u string) bool {
	_, err := url.Parse(u)
	return err == nil && urlRegex.MatchString(u)
}

func isValidAlpha(s string) bool {
	return alphaRegex.MatchString(s)
}

func isValidAlphanum(s string) bool {
	return alphaNumRegex.MatchString(s)
}

func isValidNumeric(s string) bool {
	return numericRegex.MatchString(s)
}

func isValidBase64(s string) bool {
	return base64Regex.MatchString(s) && len(s)%4 == 0
}

func isValidHostname(s string) bool {
	// Simple hostname validation
	hostnameRegex := regexp.MustCompile(`^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$`)
	return hostnameRegex.MatchString(s)
}

func isValidCidr(s string) bool {
	_, _, err := net.ParseCIDR(s)
	return err == nil
}

func isValidIP(s string) bool {
	return net.ParseIP(s) != nil
}

// init registers generated validators with the go-validation registry
func init() {
	validation.RegisterValidation("emailconfig", ValidateEmailConfig)
}

// Validate validates the EmailConfig struct using zero-reflection validation
func (s *EmailConfig) Validate() error {
	var errs *errors.FluentError = errors.NewError()

	// Validate FromAddress
	if s.FromAddress == "" {
		errs.Field("FromAddress").Required()
	}
	if !isValidEmail(s.FromAddress) {
		errs.Field("FromAddress").Email()
	}

	// Validate ReplyTo
	if !isValidEmail(s.ReplyTo) {
		errs.Field("ReplyTo").Email()
	}

	// Validate AdminEmails
	if len(s.AdminEmails) == 0 {
		errs.Field("AdminEmails").Required()
	}
	if len(s.AdminEmails) < 1 {
		errs.Field("AdminEmails").Custom("must have at least 1 items", "min")
	}
	// Dive validation for AdminEmails would validate each element
	for i, item := range s.AdminEmails {
		if !isValidEmail(item) {
			errs.Field(fmt.Sprintf("AdminEmails[%d]", i)).Email()
		}
	}

	// Validate SMTPHost
	if s.SMTPHost == "" {
		errs.Field("SMTPHost").Required()
	}
	if !isValidHostname(s.SMTPHost) {
		errs.Field("SMTPHost").Format("must be a valid hostname")
	}

	// Validate SMTPPort
	if s.SMTPPort == 0 {
		errs.Field("SMTPPort").Required()
	}
	if s.SMTPPort < 1 {
		errs.Field("SMTPPort").Min(1)
	}
	if s.SMTPPort > 65535 {
		errs.Field("SMTPPort").Max(65535)
	}

	// Validate SMTPUsername
	if s.SMTPUsername == "" {
		errs.Field("SMTPUsername").Required()
	}

	// Validate SMTPPassword
	if s.SMTPPassword == "" {
		errs.Field("SMTPPassword").Required()
	}

	if errs.HasErrors() {
		return errs
	}
	return nil
}

// ValidateEmailConfig validates EmailConfig instances for use with go-validation registry
func ValidateEmailConfig(fl validation.FieldLevel) bool {
	// This is a placeholder - actual implementation would use fl
	return true
}

