//go:generate go run ../../cmd/go-config-gen -input . -output validation_generated.go -verbose

// This file demonstrates using the generated validation code with the CLI tool
package main

// import will be added to generated file

// ServerConfig demonstrates zero reflection validation with code generation
// The Validate() method will be generated automatically by go:generate
type ServerConfig struct {
	// Server settings
	Host     string `config:"host" validate:"required,regex=^[a-zA-Z0-9.-]+$"`
	Port     int    `config:"port" validate:"required,range=1000:65535"`
	Protocol string `config:"protocol" validate:"oneof=http|https"`

	// Database
	DatabaseURL string `config:"database_url" validate:"required,url"`
	MaxConns    int    `config:"max_conns" validate:"min=1,max=100"`

	// Security
	JWTSecret  string `config:"jwt_secret" validate:"required,minlen=32"`
	AdminEmail string `config:"admin_email" validate:"required,email"`
	APIKey     string `config:"api_key" validate:"required,len=32,alphanumeric"`

	// Features
	EnableDebug bool   `config:"enable_debug"`
	LogLevel    string `config:"log_level" validate:"oneof=debug|info|warn|error"`
	Version     string `config:"version" validate:"required,regex=^v[0-9]+\\.[0-9]+\\.[0-9]+$"`
}

// The Validate() method will be generated by go:generate above
