// Code generated by go-validate. DO NOT EDIT.
// This file contains zero-reflection validation methods.
// Generated at: 2025-07-27T03:42:14-05:00

package main

import (
	"regexp"

	goconfig "github.com/mateothegreat/go-config"
)

// Pre-compiled regex patterns for validation performance
var (
	emailRegex    = regexp.MustCompile(`^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$`)
	urlRegex      = regexp.MustCompile(`^[a-zA-Z][a-zA-Z0-9+.-]*://[^\s]*$`)
	alphaRegex    = regexp.MustCompile(`^[a-zA-Z]+$`)
	alphaNumRegex = regexp.MustCompile(`^[a-zA-Z0-9]+$`)
	numericRegex  = regexp.MustCompile(`^[0-9]+$`)
)

// Validate validates the ServerConfig struct using zero-reflection validation
func (s *ServerConfig) Validate() error {

	if s.Host == "" {
		return goconfig.NewError().Field("Host").Required()
	}

	if s.Port > 65535 {
		return goconfig.NewError().Field("Port").Format("must be at most 65535")
	}

	if s.Port < 1 {
		return goconfig.NewError().Field("Port").Format("must be at least 1")
	}

	if s.ReadTimeout > 300 {
		return goconfig.NewError().Field("ReadTimeout").Format("must be at most 300")
	}

	if s.ReadTimeout < 1 {
		return goconfig.NewError().Field("ReadTimeout").Format("must be at least 1")
	}

	if s.WriteTimeout > 300 {
		return goconfig.NewError().Field("WriteTimeout").Format("must be at most 300")
	}

	if s.WriteTimeout < 1 {
		return goconfig.NewError().Field("WriteTimeout").Format("must be at least 1")
	}
	return nil
}
